# Generated by Django 3.2 on 2021-04-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('card_no', models.BigIntegerField()),
                ('exp_date', models.DateTimeField()),
                ('cvv', models.SmallIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('defa', models.CharField(max_length=1)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.CharField(max_length=1)),
                ('is_base_currency', models.CharField(max_length=1)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'currencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inven_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=10)),
                ('bought_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy_sell', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ts', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('buy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sell', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ts', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'trade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('pri', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trade_offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=60)),
                ('time_registered', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_data',
                'managed': False,
            },
        ),
    ]
