# Generated by Django 3.2 on 2021-04-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divident',
            fields=[
                ('yr2004', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2005', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2006', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2007', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2008', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2009', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2010', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2011', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2012', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2013', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2014', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2015', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2016', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2017', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2018', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2019', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2020', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yr2021', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.item')),
            ],
            options={
                'db_table': 'divident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'item_research',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('ids', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('authorid', models.CharField(max_length=10)),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'research',
                'managed': False,
            },
        ),
    ]
